#!/bin/sh

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"



# random-wallpaper $HOME/wallpapers/
wallpaper_path="${HOME}/wallpapers/"
image=$(find ${wallpaper_path}/ -type f -not -path "${wallpaper_path}/lock/*" | shuf -n 1 | xargs -I{} basename {})
swaybg -i ${wallpaper_path}/${image} > /dev/null 2>&1 &

#restart the waybar
killall -SIGUSR2 waybar
