#!/usr/bin/bash

wallpaper_path="${HOME}/wallpapers/"
image=$(find ${wallpaper_path}/ -type f -not -path "${wallpaper_path}/lock/*" | shuf -n 1 | xargs -I{} basename {})
swaybg -i ${wallpaper_path}/${image} > /dev/null 2>&1 &
