#! /bin/sh

setxkbmap -layout eu &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
~/.config/polybar/launch.sh &


if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --output DisplayPort-0 --mode 1920x1080 --rotate normal --right-of HDMI-A-0
fi

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6
bspc monitor DisplayPort-0 -d 7 8 9

bspc config pointer_modifier mod1

bspc config border_width             1
bspc config window_gap               5
bspc config split_ratio              0.55
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config focus_follows_pointer    false
bspc config pointer_follows_focus    true
bspc config focused_border_color     "#ebcb8b"

bspc rule -a Emacs desktop='^2' state=tile follow=on
