#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
nitrogen --restore &
picom &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
